/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvancedFilter {
  'categories' : Array<Category>,
  'configurations' : Array<Configuration>,
  'propertyTypes' : Array<PropertyType>,
  'statuses' : Array<Status>,
  'locations' : Array<Location>,
  'coordinateFilters' : Array<
    { 'lat' : number, 'lng' : number, 'radius' : number }
  >,
  'furnishings' : Array<Furnishing>,
  'priceRanges' : Array<[[] | [bigint], [] | [bigint]]>,
}
export type Category = { 'rental' : null } |
  { 'resale' : null } |
  { 'underConstruction' : null };
export interface CategoryDistribution {
  'region' : string,
  'resaleCount' : bigint,
  'rentalCount' : bigint,
  'regionType' : RegionType,
  'underConstructionCount' : bigint,
}
export interface CombinedAnalytics {
  'propertyDensity' : Array<PropertyDensity>,
  'furnishingDistribution' : Array<FurnishingDistribution>,
  'configurationDistribution' : Array<ConfigurationDistribution>,
  'categoryDistribution' : Array<CategoryDistribution>,
  'pricingHeatmap' : Array<PricingHeatmap>,
  'propertyTypeDistribution' : Array<PropertyTypeDistribution>,
  'regionalDistribution' : Array<RegionalDistribution>,
}
export type Configuration = { 'rk1' : null } |
  { 'bhk1' : null } |
  { 'bhk2' : null } |
  { 'bhk3' : null } |
  { 'bhk4' : null } |
  { 'bhk5' : null } |
  { 'penthouse' : null } |
  { 'jodiFlat' : null } |
  { 'bhk1_5' : null } |
  { 'bhk2_5' : null } |
  { 'bhk3_5' : null } |
  { 'bungalow' : null } |
  { 'independentHouse' : null } |
  { 'duplex' : null };
export interface ConfigurationDistribution {
  'region' : string,
  'bungalowCount' : bigint,
  'bhk4Count' : bigint,
  'bhk1_5Count' : bigint,
  'bhk2Count' : bigint,
  'bhk2_5Count' : bigint,
  'rk1Count' : bigint,
  'independentHouseCount' : bigint,
  'jodiFlatCount' : bigint,
  'bhk5Count' : bigint,
  'bhk3_5Count' : bigint,
  'bhk3Count' : bigint,
  'bhk1Count' : bigint,
  'regionType' : RegionType,
  'duplexCount' : bigint,
  'penthouseCount' : bigint,
}
export interface Coordinates { 'lat' : number, 'lng' : number }
export type ExternalBlob = Uint8Array;
export type Furnishing = { 'semiFurnished' : null } |
  { 'furnished' : null } |
  { 'unfurnished' : null };
export interface FurnishingDistribution {
  'region' : string,
  'furnishedCount' : bigint,
  'unfurnishedCount' : bigint,
  'semiFurnishedCount' : bigint,
  'regionType' : RegionType,
}
export interface Inquiry {
  'id' : string,
  'customerName' : string,
  'status' : Status__1,
  'contactInfo' : string,
  'source' : Source,
  'assignedAgent' : Principal,
  'createdAt' : Time,
  'propertyId' : string,
  'updatedAt' : Time,
  'notes' : string,
}
export interface Location {
  'roadName' : string,
  'area' : string,
  'city' : string,
  'suburb' : string,
}
export interface PricingHeatmap {
  'region' : string,
  'averagePrice' : [] | [bigint],
  'priceRange' : { 'maxPrice' : [] | [bigint], 'minPrice' : [] | [bigint] },
  'regionType' : RegionType,
}
export interface Profile {
  'id' : Principal,
  'active' : boolean,
  'contactInfo' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : Role,
  'updatedAt' : Time,
}
export interface Property {
  'id' : string,
  'status' : Status,
  'title' : string,
  'propertyType' : PropertyType,
  'listedBy' : Principal,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'category' : Category,
  'configuration' : Configuration,
  'price' : bigint,
  'furnishing' : Furnishing,
  'location' : Location,
  'coordinates' : Coordinates,
  'images' : Array<ExternalBlob>,
}
export interface PropertyDensity {
  'region' : string,
  'propertyCount' : bigint,
  'regionType' : RegionType,
}
export type PropertyType = { 'commercial' : null } |
  { 'residential' : null } |
  { 'industrial' : null };
export interface PropertyTypeDistribution {
  'region' : string,
  'commercialCount' : bigint,
  'industrialCount' : bigint,
  'residentialCount' : bigint,
  'regionType' : RegionType,
}
export type RegionType = { 'area' : null } |
  { 'city' : null } |
  { 'neighborhood' : null } |
  { 'zone' : null } |
  { 'suburb' : null };
export interface RegionalDistribution {
  'region' : string,
  'averagePrice' : [] | [bigint],
  'priceRange' : { 'maxPrice' : [] | [bigint], 'minPrice' : [] | [bigint] },
  'furnishingDistribution' : {
    'semiFurnished' : bigint,
    'furnished' : bigint,
    'unfurnished' : bigint,
  },
  'configurationDistribution' : {
    'rk1' : bigint,
    'bhk1' : bigint,
    'bhk2' : bigint,
    'bhk3' : bigint,
    'bhk4' : bigint,
    'bhk5' : bigint,
    'penthouse' : bigint,
    'jodiFlat' : bigint,
    'bhk1_5' : bigint,
    'bhk2_5' : bigint,
    'bhk3_5' : bigint,
    'bungalow' : bigint,
    'independentHouse' : bigint,
    'duplex' : bigint,
  },
  'categoryDistribution' : {
    'rental' : bigint,
    'resale' : bigint,
    'underConstruction' : bigint,
  },
  'propertyCount' : bigint,
  'propertyTypeDistribution' : {
    'commercial' : bigint,
    'residential' : bigint,
    'industrial' : bigint,
  },
  'regionType' : RegionType,
}
export type Role = { 'admin' : null } |
  { 'agent' : null } |
  { 'juniorAgent' : null } |
  { 'assistant' : null };
export interface SearchCriteria {
  'lat' : [] | [number],
  'lng' : [] | [number],
  'status' : [] | [Status],
  'roadName' : [] | [string],
  'propertyType' : [] | [PropertyType],
  'area' : [] | [string],
  'city' : [] | [string],
  'maxPrice' : [] | [bigint],
  'suburb' : [] | [string],
  'category' : [] | [Category],
  'radius' : [] | [number],
  'configuration' : [] | [Configuration],
  'minPrice' : [] | [bigint],
  'furnishing' : [] | [Furnishing],
}
export type Source = { 'referral' : null } |
  { 'website' : null } |
  { 'walkIn' : null } |
  { 'phone' : null } |
  { 'socialMedia' : null };
export type Status = { 'rented' : null } |
  { 'sold' : null } |
  { 'underContract' : null } |
  { 'available' : null };
export type Status__1 = { 'new' : null } |
  { 'closed' : null } |
  { 'followUp' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile { 'contactInfo' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAgent' : ActorMethod<[Principal, string, string, Role], undefined>,
  'addInquiry' : ActorMethod<
    [string, string, string, Source, Principal, string],
    string
  >,
  'addProperty' : ActorMethod<
    [
      string,
      string,
      Location,
      Coordinates,
      bigint,
      Category,
      PropertyType,
      Configuration,
      Furnishing,
      Array<ExternalBlob>,
    ],
    string
  >,
  'advancedFilterProperties' : ActorMethod<[AdvancedFilter], Array<Property>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateAgent' : ActorMethod<[Principal], undefined>,
  'filterPropertiesByCategoryAndConfig' : ActorMethod<
    [Category, Configuration],
    Array<Property>
  >,
  'filterPropertiesByConfiguration' : ActorMethod<
    [Configuration],
    Array<Property>
  >,
  'getAgent' : ActorMethod<[Principal], Profile>,
  'getAllAgents' : ActorMethod<[], Array<Profile>>,
  'getAllCities' : ActorMethod<[], Array<string>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAreasForSuburb' : ActorMethod<[string, string], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCombinedAnalytics' : ActorMethod<[], CombinedAnalytics>,
  'getConfigurationDistribution' : ActorMethod<
    [],
    Array<ConfigurationDistribution>
  >,
  'getFurnishingDistribution' : ActorMethod<[], Array<FurnishingDistribution>>,
  'getInquiriesByAgent' : ActorMethod<[Principal], Array<Inquiry>>,
  'getInquiriesByProperty' : ActorMethod<[string], Array<Inquiry>>,
  'getInquiry' : ActorMethod<[string], Inquiry>,
  'getPropertiesByCategory' : ActorMethod<[Category], Array<Property>>,
  'getPropertiesByCategoryAndType' : ActorMethod<
    [Category, PropertyType],
    Array<Property>
  >,
  'getPropertiesByPropertyType' : ActorMethod<[PropertyType], Array<Property>>,
  'getProperty' : ActorMethod<[string], Property>,
  'getSuburbsForCity' : ActorMethod<[string], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetToFreshDraft' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAndFilterProperties' : ActorMethod<[SearchCriteria], Array<Property>>,
  'updateAgent' : ActorMethod<[Principal, string, string, Role], undefined>,
  'updateInquiry' : ActorMethod<
    [string, string, string, Source, Status__1, Principal, string],
    undefined
  >,
  'updateProperty' : ActorMethod<
    [
      string,
      string,
      string,
      Location,
      Coordinates,
      bigint,
      Category,
      PropertyType,
      Configuration,
      Furnishing,
      Status,
      Array<ExternalBlob>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];