/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'agent' : IDL.Null,
  'juniorAgent' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Source = IDL.Variant({
  'referral' : IDL.Null,
  'website' : IDL.Null,
  'walkIn' : IDL.Null,
  'phone' : IDL.Null,
  'socialMedia' : IDL.Null,
});
export const Location = IDL.Record({
  'roadName' : IDL.Text,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'suburb' : IDL.Text,
});
export const Coordinates = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const Category = IDL.Variant({
  'rental' : IDL.Null,
  'resale' : IDL.Null,
  'underConstruction' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
  'industrial' : IDL.Null,
});
export const Configuration = IDL.Variant({
  'rk1' : IDL.Null,
  'bhk1' : IDL.Null,
  'bhk2' : IDL.Null,
  'bhk3' : IDL.Null,
  'bhk4' : IDL.Null,
  'bhk5' : IDL.Null,
  'penthouse' : IDL.Null,
  'jodiFlat' : IDL.Null,
  'bhk1_5' : IDL.Null,
  'bhk2_5' : IDL.Null,
  'bhk3_5' : IDL.Null,
  'bungalow' : IDL.Null,
  'independentHouse' : IDL.Null,
  'duplex' : IDL.Null,
});
export const Furnishing = IDL.Variant({
  'semiFurnished' : IDL.Null,
  'furnished' : IDL.Null,
  'unfurnished' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Status = IDL.Variant({
  'rented' : IDL.Null,
  'sold' : IDL.Null,
  'underContract' : IDL.Null,
  'available' : IDL.Null,
});
export const AdvancedFilter = IDL.Record({
  'categories' : IDL.Vec(Category),
  'configurations' : IDL.Vec(Configuration),
  'propertyTypes' : IDL.Vec(PropertyType),
  'statuses' : IDL.Vec(Status),
  'locations' : IDL.Vec(Location),
  'coordinateFilters' : IDL.Vec(
    IDL.Record({
      'lat' : IDL.Float64,
      'lng' : IDL.Float64,
      'radius' : IDL.Float64,
    })
  ),
  'furnishings' : IDL.Vec(Furnishing),
  'priceRanges' : IDL.Vec(IDL.Tuple(IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat))),
});
export const Time = IDL.Int;
export const Property = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'listedBy' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'category' : Category,
  'configuration' : Configuration,
  'price' : IDL.Nat,
  'furnishing' : Furnishing,
  'location' : Location,
  'coordinates' : Coordinates,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Profile = IDL.Record({
  'id' : IDL.Principal,
  'active' : IDL.Bool,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : Role,
  'updatedAt' : Time,
});
export const Status__1 = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'followUp' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : Status__1,
  'contactInfo' : IDL.Text,
  'source' : Source,
  'assignedAgent' : IDL.Principal,
  'createdAt' : Time,
  'propertyId' : IDL.Text,
  'updatedAt' : Time,
  'notes' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const RegionType = IDL.Variant({
  'area' : IDL.Null,
  'city' : IDL.Null,
  'neighborhood' : IDL.Null,
  'zone' : IDL.Null,
  'suburb' : IDL.Null,
});
export const PropertyDensity = IDL.Record({
  'region' : IDL.Text,
  'propertyCount' : IDL.Nat,
  'regionType' : RegionType,
});
export const FurnishingDistribution = IDL.Record({
  'region' : IDL.Text,
  'furnishedCount' : IDL.Nat,
  'unfurnishedCount' : IDL.Nat,
  'semiFurnishedCount' : IDL.Nat,
  'regionType' : RegionType,
});
export const ConfigurationDistribution = IDL.Record({
  'region' : IDL.Text,
  'bungalowCount' : IDL.Nat,
  'bhk4Count' : IDL.Nat,
  'bhk1_5Count' : IDL.Nat,
  'bhk2Count' : IDL.Nat,
  'bhk2_5Count' : IDL.Nat,
  'rk1Count' : IDL.Nat,
  'independentHouseCount' : IDL.Nat,
  'jodiFlatCount' : IDL.Nat,
  'bhk5Count' : IDL.Nat,
  'bhk3_5Count' : IDL.Nat,
  'bhk3Count' : IDL.Nat,
  'bhk1Count' : IDL.Nat,
  'regionType' : RegionType,
  'duplexCount' : IDL.Nat,
  'penthouseCount' : IDL.Nat,
});
export const CategoryDistribution = IDL.Record({
  'region' : IDL.Text,
  'resaleCount' : IDL.Nat,
  'rentalCount' : IDL.Nat,
  'regionType' : RegionType,
  'underConstructionCount' : IDL.Nat,
});
export const PricingHeatmap = IDL.Record({
  'region' : IDL.Text,
  'averagePrice' : IDL.Opt(IDL.Nat),
  'priceRange' : IDL.Record({
    'maxPrice' : IDL.Opt(IDL.Nat),
    'minPrice' : IDL.Opt(IDL.Nat),
  }),
  'regionType' : RegionType,
});
export const PropertyTypeDistribution = IDL.Record({
  'region' : IDL.Text,
  'commercialCount' : IDL.Nat,
  'industrialCount' : IDL.Nat,
  'residentialCount' : IDL.Nat,
  'regionType' : RegionType,
});
export const RegionalDistribution = IDL.Record({
  'region' : IDL.Text,
  'averagePrice' : IDL.Opt(IDL.Nat),
  'priceRange' : IDL.Record({
    'maxPrice' : IDL.Opt(IDL.Nat),
    'minPrice' : IDL.Opt(IDL.Nat),
  }),
  'furnishingDistribution' : IDL.Record({
    'semiFurnished' : IDL.Nat,
    'furnished' : IDL.Nat,
    'unfurnished' : IDL.Nat,
  }),
  'configurationDistribution' : IDL.Record({
    'rk1' : IDL.Nat,
    'bhk1' : IDL.Nat,
    'bhk2' : IDL.Nat,
    'bhk3' : IDL.Nat,
    'bhk4' : IDL.Nat,
    'bhk5' : IDL.Nat,
    'penthouse' : IDL.Nat,
    'jodiFlat' : IDL.Nat,
    'bhk1_5' : IDL.Nat,
    'bhk2_5' : IDL.Nat,
    'bhk3_5' : IDL.Nat,
    'bungalow' : IDL.Nat,
    'independentHouse' : IDL.Nat,
    'duplex' : IDL.Nat,
  }),
  'categoryDistribution' : IDL.Record({
    'rental' : IDL.Nat,
    'resale' : IDL.Nat,
    'underConstruction' : IDL.Nat,
  }),
  'propertyCount' : IDL.Nat,
  'propertyTypeDistribution' : IDL.Record({
    'commercial' : IDL.Nat,
    'residential' : IDL.Nat,
    'industrial' : IDL.Nat,
  }),
  'regionType' : RegionType,
});
export const CombinedAnalytics = IDL.Record({
  'propertyDensity' : IDL.Vec(PropertyDensity),
  'furnishingDistribution' : IDL.Vec(FurnishingDistribution),
  'configurationDistribution' : IDL.Vec(ConfigurationDistribution),
  'categoryDistribution' : IDL.Vec(CategoryDistribution),
  'pricingHeatmap' : IDL.Vec(PricingHeatmap),
  'propertyTypeDistribution' : IDL.Vec(PropertyTypeDistribution),
  'regionalDistribution' : IDL.Vec(RegionalDistribution),
});
export const SearchCriteria = IDL.Record({
  'lat' : IDL.Opt(IDL.Float64),
  'lng' : IDL.Opt(IDL.Float64),
  'status' : IDL.Opt(Status),
  'roadName' : IDL.Opt(IDL.Text),
  'propertyType' : IDL.Opt(PropertyType),
  'area' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'suburb' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
  'radius' : IDL.Opt(IDL.Float64),
  'configuration' : IDL.Opt(Configuration),
  'minPrice' : IDL.Opt(IDL.Nat),
  'furnishing' : IDL.Opt(Furnishing),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAgent' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text, Role], [], []),
  'addInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Source, IDL.Principal, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addProperty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Location,
        Coordinates,
        IDL.Nat,
        Category,
        PropertyType,
        Configuration,
        Furnishing,
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'advancedFilterProperties' : IDL.Func(
      [AdvancedFilter],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateAgent' : IDL.Func([IDL.Principal], [], []),
  'filterPropertiesByCategoryAndConfig' : IDL.Func(
      [Category, Configuration],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'filterPropertiesByConfiguration' : IDL.Func(
      [Configuration],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getAgent' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getAllAgents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAllCities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAreasForSuburb' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCombinedAnalytics' : IDL.Func([], [CombinedAnalytics], ['query']),
  'getConfigurationDistribution' : IDL.Func(
      [],
      [IDL.Vec(ConfigurationDistribution)],
      ['query'],
    ),
  'getFurnishingDistribution' : IDL.Func(
      [],
      [IDL.Vec(FurnishingDistribution)],
      ['query'],
    ),
  'getInquiriesByAgent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getInquiriesByProperty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getInquiry' : IDL.Func([IDL.Text], [Inquiry], ['query']),
  'getPropertiesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByCategoryAndType' : IDL.Func(
      [Category, PropertyType],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByPropertyType' : IDL.Func(
      [PropertyType],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getProperty' : IDL.Func([IDL.Text], [Property], ['query']),
  'getSuburbsForCity' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetToFreshDraft' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAndFilterProperties' : IDL.Func(
      [SearchCriteria],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'updateAgent' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text, Role], [], []),
  'updateInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Source,
        Status__1,
        IDL.Principal,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateProperty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Location,
        Coordinates,
        IDL.Nat,
        Category,
        PropertyType,
        Configuration,
        Furnishing,
        Status,
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'agent' : IDL.Null,
    'juniorAgent' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const Source = IDL.Variant({
    'referral' : IDL.Null,
    'website' : IDL.Null,
    'walkIn' : IDL.Null,
    'phone' : IDL.Null,
    'socialMedia' : IDL.Null,
  });
  const Location = IDL.Record({
    'roadName' : IDL.Text,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'suburb' : IDL.Text,
  });
  const Coordinates = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const Category = IDL.Variant({
    'rental' : IDL.Null,
    'resale' : IDL.Null,
    'underConstruction' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
    'industrial' : IDL.Null,
  });
  const Configuration = IDL.Variant({
    'rk1' : IDL.Null,
    'bhk1' : IDL.Null,
    'bhk2' : IDL.Null,
    'bhk3' : IDL.Null,
    'bhk4' : IDL.Null,
    'bhk5' : IDL.Null,
    'penthouse' : IDL.Null,
    'jodiFlat' : IDL.Null,
    'bhk1_5' : IDL.Null,
    'bhk2_5' : IDL.Null,
    'bhk3_5' : IDL.Null,
    'bungalow' : IDL.Null,
    'independentHouse' : IDL.Null,
    'duplex' : IDL.Null,
  });
  const Furnishing = IDL.Variant({
    'semiFurnished' : IDL.Null,
    'furnished' : IDL.Null,
    'unfurnished' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Status = IDL.Variant({
    'rented' : IDL.Null,
    'sold' : IDL.Null,
    'underContract' : IDL.Null,
    'available' : IDL.Null,
  });
  const AdvancedFilter = IDL.Record({
    'categories' : IDL.Vec(Category),
    'configurations' : IDL.Vec(Configuration),
    'propertyTypes' : IDL.Vec(PropertyType),
    'statuses' : IDL.Vec(Status),
    'locations' : IDL.Vec(Location),
    'coordinateFilters' : IDL.Vec(
      IDL.Record({
        'lat' : IDL.Float64,
        'lng' : IDL.Float64,
        'radius' : IDL.Float64,
      })
    ),
    'furnishings' : IDL.Vec(Furnishing),
    'priceRanges' : IDL.Vec(IDL.Tuple(IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat))),
  });
  const Time = IDL.Int;
  const Property = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'listedBy' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'category' : Category,
    'configuration' : Configuration,
    'price' : IDL.Nat,
    'furnishing' : Furnishing,
    'location' : Location,
    'coordinates' : Coordinates,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Profile = IDL.Record({
    'id' : IDL.Principal,
    'active' : IDL.Bool,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : Role,
    'updatedAt' : Time,
  });
  const Status__1 = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'followUp' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : Status__1,
    'contactInfo' : IDL.Text,
    'source' : Source,
    'assignedAgent' : IDL.Principal,
    'createdAt' : Time,
    'propertyId' : IDL.Text,
    'updatedAt' : Time,
    'notes' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const RegionType = IDL.Variant({
    'area' : IDL.Null,
    'city' : IDL.Null,
    'neighborhood' : IDL.Null,
    'zone' : IDL.Null,
    'suburb' : IDL.Null,
  });
  const PropertyDensity = IDL.Record({
    'region' : IDL.Text,
    'propertyCount' : IDL.Nat,
    'regionType' : RegionType,
  });
  const FurnishingDistribution = IDL.Record({
    'region' : IDL.Text,
    'furnishedCount' : IDL.Nat,
    'unfurnishedCount' : IDL.Nat,
    'semiFurnishedCount' : IDL.Nat,
    'regionType' : RegionType,
  });
  const ConfigurationDistribution = IDL.Record({
    'region' : IDL.Text,
    'bungalowCount' : IDL.Nat,
    'bhk4Count' : IDL.Nat,
    'bhk1_5Count' : IDL.Nat,
    'bhk2Count' : IDL.Nat,
    'bhk2_5Count' : IDL.Nat,
    'rk1Count' : IDL.Nat,
    'independentHouseCount' : IDL.Nat,
    'jodiFlatCount' : IDL.Nat,
    'bhk5Count' : IDL.Nat,
    'bhk3_5Count' : IDL.Nat,
    'bhk3Count' : IDL.Nat,
    'bhk1Count' : IDL.Nat,
    'regionType' : RegionType,
    'duplexCount' : IDL.Nat,
    'penthouseCount' : IDL.Nat,
  });
  const CategoryDistribution = IDL.Record({
    'region' : IDL.Text,
    'resaleCount' : IDL.Nat,
    'rentalCount' : IDL.Nat,
    'regionType' : RegionType,
    'underConstructionCount' : IDL.Nat,
  });
  const PricingHeatmap = IDL.Record({
    'region' : IDL.Text,
    'averagePrice' : IDL.Opt(IDL.Nat),
    'priceRange' : IDL.Record({
      'maxPrice' : IDL.Opt(IDL.Nat),
      'minPrice' : IDL.Opt(IDL.Nat),
    }),
    'regionType' : RegionType,
  });
  const PropertyTypeDistribution = IDL.Record({
    'region' : IDL.Text,
    'commercialCount' : IDL.Nat,
    'industrialCount' : IDL.Nat,
    'residentialCount' : IDL.Nat,
    'regionType' : RegionType,
  });
  const RegionalDistribution = IDL.Record({
    'region' : IDL.Text,
    'averagePrice' : IDL.Opt(IDL.Nat),
    'priceRange' : IDL.Record({
      'maxPrice' : IDL.Opt(IDL.Nat),
      'minPrice' : IDL.Opt(IDL.Nat),
    }),
    'furnishingDistribution' : IDL.Record({
      'semiFurnished' : IDL.Nat,
      'furnished' : IDL.Nat,
      'unfurnished' : IDL.Nat,
    }),
    'configurationDistribution' : IDL.Record({
      'rk1' : IDL.Nat,
      'bhk1' : IDL.Nat,
      'bhk2' : IDL.Nat,
      'bhk3' : IDL.Nat,
      'bhk4' : IDL.Nat,
      'bhk5' : IDL.Nat,
      'penthouse' : IDL.Nat,
      'jodiFlat' : IDL.Nat,
      'bhk1_5' : IDL.Nat,
      'bhk2_5' : IDL.Nat,
      'bhk3_5' : IDL.Nat,
      'bungalow' : IDL.Nat,
      'independentHouse' : IDL.Nat,
      'duplex' : IDL.Nat,
    }),
    'categoryDistribution' : IDL.Record({
      'rental' : IDL.Nat,
      'resale' : IDL.Nat,
      'underConstruction' : IDL.Nat,
    }),
    'propertyCount' : IDL.Nat,
    'propertyTypeDistribution' : IDL.Record({
      'commercial' : IDL.Nat,
      'residential' : IDL.Nat,
      'industrial' : IDL.Nat,
    }),
    'regionType' : RegionType,
  });
  const CombinedAnalytics = IDL.Record({
    'propertyDensity' : IDL.Vec(PropertyDensity),
    'furnishingDistribution' : IDL.Vec(FurnishingDistribution),
    'configurationDistribution' : IDL.Vec(ConfigurationDistribution),
    'categoryDistribution' : IDL.Vec(CategoryDistribution),
    'pricingHeatmap' : IDL.Vec(PricingHeatmap),
    'propertyTypeDistribution' : IDL.Vec(PropertyTypeDistribution),
    'regionalDistribution' : IDL.Vec(RegionalDistribution),
  });
  const SearchCriteria = IDL.Record({
    'lat' : IDL.Opt(IDL.Float64),
    'lng' : IDL.Opt(IDL.Float64),
    'status' : IDL.Opt(Status),
    'roadName' : IDL.Opt(IDL.Text),
    'propertyType' : IDL.Opt(PropertyType),
    'area' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'suburb' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
    'radius' : IDL.Opt(IDL.Float64),
    'configuration' : IDL.Opt(Configuration),
    'minPrice' : IDL.Opt(IDL.Nat),
    'furnishing' : IDL.Opt(Furnishing),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAgent' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text, Role], [], []),
    'addInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Source, IDL.Principal, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Location,
          Coordinates,
          IDL.Nat,
          Category,
          PropertyType,
          Configuration,
          Furnishing,
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'advancedFilterProperties' : IDL.Func(
        [AdvancedFilter],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateAgent' : IDL.Func([IDL.Principal], [], []),
    'filterPropertiesByCategoryAndConfig' : IDL.Func(
        [Category, Configuration],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'filterPropertiesByConfiguration' : IDL.Func(
        [Configuration],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getAgent' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getAllAgents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAllCities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAreasForSuburb' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCombinedAnalytics' : IDL.Func([], [CombinedAnalytics], ['query']),
    'getConfigurationDistribution' : IDL.Func(
        [],
        [IDL.Vec(ConfigurationDistribution)],
        ['query'],
      ),
    'getFurnishingDistribution' : IDL.Func(
        [],
        [IDL.Vec(FurnishingDistribution)],
        ['query'],
      ),
    'getInquiriesByAgent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiriesByProperty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiry' : IDL.Func([IDL.Text], [Inquiry], ['query']),
    'getPropertiesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByCategoryAndType' : IDL.Func(
        [Category, PropertyType],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByPropertyType' : IDL.Func(
        [PropertyType],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getProperty' : IDL.Func([IDL.Text], [Property], ['query']),
    'getSuburbsForCity' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetToFreshDraft' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAndFilterProperties' : IDL.Func(
        [SearchCriteria],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'updateAgent' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text, Role], [], []),
    'updateInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Source,
          Status__1,
          IDL.Principal,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Location,
          Coordinates,
          IDL.Nat,
          Category,
          PropertyType,
          Configuration,
          Furnishing,
          Status,
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };