/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    roadName: string;
    area: string;
    city: string;
    suburb: string;
}
export interface PropertyTypeDistribution {
    region: string;
    commercialCount: bigint;
    industrialCount: bigint;
    residentialCount: bigint;
    regionType: RegionType;
}
export interface FurnishingDistribution {
    region: string;
    furnishedCount: bigint;
    unfurnishedCount: bigint;
    semiFurnishedCount: bigint;
    regionType: RegionType;
}
export type Time = bigint;
export interface ConfigurationDistribution {
    region: string;
    bungalowCount: bigint;
    bhk4Count: bigint;
    bhk1_5Count: bigint;
    bhk2Count: bigint;
    bhk2_5Count: bigint;
    rk1Count: bigint;
    independentHouseCount: bigint;
    jodiFlatCount: bigint;
    bhk5Count: bigint;
    bhk3_5Count: bigint;
    bhk3Count: bigint;
    bhk1Count: bigint;
    regionType: RegionType;
    duplexCount: bigint;
    penthouseCount: bigint;
}
export interface Coordinates {
    lat: number;
    lng: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UserProfile {
    contactInfo: string;
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Profile {
    id: Principal;
    active: boolean;
    contactInfo: string;
    name: string;
    createdAt: Time;
    role: Role;
    updatedAt: Time;
}
export interface Property {
    id: string;
    status: Status;
    title: string;
    propertyType: PropertyType;
    listedBy: Principal;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    category: Category;
    configuration: Configuration;
    price: bigint;
    furnishing: Furnishing;
    location: Location;
    coordinates: Coordinates;
    images: Array<ExternalBlob>;
}
export interface CategoryDistribution {
    region: string;
    resaleCount: bigint;
    rentalCount: bigint;
    regionType: RegionType;
    underConstructionCount: bigint;
}
export interface SearchCriteria {
    lat?: number;
    lng?: number;
    status?: Status;
    roadName?: string;
    propertyType?: PropertyType;
    area?: string;
    city?: string;
    maxPrice?: bigint;
    suburb?: string;
    category?: Category;
    radius?: number;
    configuration?: Configuration;
    minPrice?: bigint;
    furnishing?: Furnishing;
}
export interface AdvancedFilter {
    categories: Array<Category>;
    configurations: Array<Configuration>;
    propertyTypes: Array<PropertyType>;
    statuses: Array<Status>;
    locations: Array<Location>;
    coordinateFilters: Array<{
        lat: number;
        lng: number;
        radius: number;
    }>;
    furnishings: Array<Furnishing>;
    priceRanges: Array<[bigint | null, bigint | null]>;
}
export interface PropertyDensity {
    region: string;
    propertyCount: bigint;
    regionType: RegionType;
}
export interface RegionalDistribution {
    region: string;
    averagePrice?: bigint;
    priceRange: {
        maxPrice?: bigint;
        minPrice?: bigint;
    };
    furnishingDistribution: {
        semiFurnished: bigint;
        furnished: bigint;
        unfurnished: bigint;
    };
    configurationDistribution: {
        rk1: bigint;
        bhk1: bigint;
        bhk2: bigint;
        bhk3: bigint;
        bhk4: bigint;
        bhk5: bigint;
        penthouse: bigint;
        jodiFlat: bigint;
        bhk1_5: bigint;
        bhk2_5: bigint;
        bhk3_5: bigint;
        bungalow: bigint;
        independentHouse: bigint;
        duplex: bigint;
    };
    categoryDistribution: {
        rental: bigint;
        resale: bigint;
        underConstruction: bigint;
    };
    propertyCount: bigint;
    propertyTypeDistribution: {
        commercial: bigint;
        residential: bigint;
        industrial: bigint;
    };
    regionType: RegionType;
}
export interface PricingHeatmap {
    region: string;
    averagePrice?: bigint;
    priceRange: {
        maxPrice?: bigint;
        minPrice?: bigint;
    };
    regionType: RegionType;
}
export interface CombinedAnalytics {
    propertyDensity: Array<PropertyDensity>;
    furnishingDistribution: Array<FurnishingDistribution>;
    configurationDistribution: Array<ConfigurationDistribution>;
    categoryDistribution: Array<CategoryDistribution>;
    pricingHeatmap: Array<PricingHeatmap>;
    propertyTypeDistribution: Array<PropertyTypeDistribution>;
    regionalDistribution: Array<RegionalDistribution>;
}
export interface Inquiry {
    id: string;
    customerName: string;
    status: Status__1;
    contactInfo: string;
    source: Source;
    assignedAgent: Principal;
    createdAt: Time;
    propertyId: string;
    updatedAt: Time;
    notes: string;
}
export enum Category {
    rental = "rental",
    resale = "resale",
    underConstruction = "underConstruction"
}
export enum Configuration {
    rk1 = "rk1",
    bhk1 = "bhk1",
    bhk2 = "bhk2",
    bhk3 = "bhk3",
    bhk4 = "bhk4",
    bhk5 = "bhk5",
    penthouse = "penthouse",
    jodiFlat = "jodiFlat",
    bhk1_5 = "bhk1_5",
    bhk2_5 = "bhk2_5",
    bhk3_5 = "bhk3_5",
    bungalow = "bungalow",
    independentHouse = "independentHouse",
    duplex = "duplex"
}
export enum Furnishing {
    semiFurnished = "semiFurnished",
    furnished = "furnished",
    unfurnished = "unfurnished"
}
export enum PropertyType {
    commercial = "commercial",
    residential = "residential",
    industrial = "industrial"
}
export enum RegionType {
    area = "area",
    city = "city",
    neighborhood = "neighborhood",
    zone = "zone",
    suburb = "suburb"
}
export enum Role {
    admin = "admin",
    agent = "agent",
    juniorAgent = "juniorAgent",
    assistant = "assistant"
}
export enum Source {
    referral = "referral",
    website = "website",
    walkIn = "walkIn",
    phone = "phone",
    socialMedia = "socialMedia"
}
export enum Status {
    rented = "rented",
    sold = "sold",
    underContract = "underContract",
    available = "available"
}
export enum Status__1 {
    new_ = "new",
    closed = "closed",
    followUp = "followUp",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAgent(agentPrincipal: Principal, name: string, contactInfo: string, role: Role): Promise<void>;
    addInquiry(propertyId: string, customerName: string, contactInfo: string, source: Source, assignedAgent: Principal, notes: string): Promise<string>;
    addProperty(title: string, description: string, location: Location, coordinates: Coordinates, price: bigint, category: Category, propertyType: PropertyType, configuration: Configuration, furnishing: Furnishing, images: Array<ExternalBlob>): Promise<string>;
    advancedFilterProperties(advancedFilters: AdvancedFilter): Promise<Array<Property>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deactivateAgent(agentId: Principal): Promise<void>;
    filterPropertiesByCategoryAndConfig(category: Category, configuration: Configuration): Promise<Array<Property>>;
    filterPropertiesByConfiguration(configuration: Configuration): Promise<Array<Property>>;
    getAgent(agentId: Principal): Promise<Profile>;
    getAllAgents(): Promise<Array<Profile>>;
    getAllCities(): Promise<Array<string>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllProperties(): Promise<Array<Property>>;
    getAreasForSuburb(city: string, suburb: string): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCombinedAnalytics(): Promise<CombinedAnalytics>;
    getConfigurationDistribution(): Promise<Array<ConfigurationDistribution>>;
    getFurnishingDistribution(): Promise<Array<FurnishingDistribution>>;
    getInquiriesByAgent(agentId: Principal): Promise<Array<Inquiry>>;
    getInquiriesByProperty(propertyId: string): Promise<Array<Inquiry>>;
    getInquiry(inquiryId: string): Promise<Inquiry>;
    getPropertiesByCategory(category: Category): Promise<Array<Property>>;
    getPropertiesByCategoryAndType(category: Category, propertyType: PropertyType): Promise<Array<Property>>;
    getPropertiesByPropertyType(propertyType: PropertyType): Promise<Array<Property>>;
    getProperty(propertyId: string): Promise<Property>;
    getSuburbsForCity(city: string): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    resetToFreshDraft(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAndFilterProperties(criteria: SearchCriteria): Promise<Array<Property>>;
    updateAgent(agentId: Principal, name: string, contactInfo: string, role: Role): Promise<void>;
    updateInquiry(inquiryId: string, customerName: string, contactInfo: string, source: Source, status: Status__1, assignedAgent: Principal, notes: string): Promise<void>;
    updateProperty(propertyId: string, title: string, description: string, location: Location, coordinates: Coordinates, price: bigint, category: Category, propertyType: PropertyType, configuration: Configuration, furnishing: Furnishing, status: Status, images: Array<ExternalBlob>): Promise<void>;
}
import type { AdvancedFilter as _AdvancedFilter, Category as _Category, CategoryDistribution as _CategoryDistribution, CombinedAnalytics as _CombinedAnalytics, Configuration as _Configuration, ConfigurationDistribution as _ConfigurationDistribution, Coordinates as _Coordinates, ExternalBlob as _ExternalBlob, Furnishing as _Furnishing, FurnishingDistribution as _FurnishingDistribution, Inquiry as _Inquiry, Location as _Location, PricingHeatmap as _PricingHeatmap, Profile as _Profile, Property as _Property, PropertyDensity as _PropertyDensity, PropertyType as _PropertyType, PropertyTypeDistribution as _PropertyTypeDistribution, RegionType as _RegionType, RegionalDistribution as _RegionalDistribution, Role as _Role, SearchCriteria as _SearchCriteria, Source as _Source, Status as _Status, Status__1 as _Status__1, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAgent(arg0: Principal, arg1: string, arg2: string, arg3: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAgent(arg0, arg1, arg2, to_candid_Role_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAgent(arg0, arg1, arg2, to_candid_Role_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addInquiry(arg0: string, arg1: string, arg2: string, arg3: Source, arg4: Principal, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addInquiry(arg0, arg1, arg2, to_candid_Source_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInquiry(arg0, arg1, arg2, to_candid_Source_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async addProperty(arg0: string, arg1: string, arg2: Location, arg3: Coordinates, arg4: bigint, arg5: Category, arg6: PropertyType, arg7: Configuration, arg8: Furnishing, arg9: Array<ExternalBlob>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addProperty(arg0, arg1, arg2, arg3, arg4, to_candid_Category_n12(this._uploadFile, this._downloadFile, arg5), to_candid_PropertyType_n14(this._uploadFile, this._downloadFile, arg6), to_candid_Configuration_n16(this._uploadFile, this._downloadFile, arg7), to_candid_Furnishing_n18(this._uploadFile, this._downloadFile, arg8), await to_candid_vec_n20(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProperty(arg0, arg1, arg2, arg3, arg4, to_candid_Category_n12(this._uploadFile, this._downloadFile, arg5), to_candid_PropertyType_n14(this._uploadFile, this._downloadFile, arg6), to_candid_Configuration_n16(this._uploadFile, this._downloadFile, arg7), to_candid_Furnishing_n18(this._uploadFile, this._downloadFile, arg8), await to_candid_vec_n20(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async advancedFilterProperties(arg0: AdvancedFilter): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.advancedFilterProperties(to_candid_AdvancedFilter_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.advancedFilterProperties(to_candid_AdvancedFilter_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deactivateAgent(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateAgent(arg0);
            return result;
        }
    }
    async filterPropertiesByCategoryAndConfig(arg0: Category, arg1: Configuration): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPropertiesByCategoryAndConfig(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0), to_candid_Configuration_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPropertiesByCategoryAndConfig(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0), to_candid_Configuration_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterPropertiesByConfiguration(arg0: Configuration): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPropertiesByConfiguration(to_candid_Configuration_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPropertiesByConfiguration(to_candid_Configuration_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgent(arg0: Principal): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgent(arg0);
                return from_candid_Profile_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgent(arg0);
            return from_candid_Profile_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAgents(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgents();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgents();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCities(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCities();
            return result;
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProperties();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProperties();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAreasForSuburb(arg0: string, arg1: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAreasForSuburb(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAreasForSuburb(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCombinedAnalytics(): Promise<CombinedAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getCombinedAnalytics();
                return from_candid_CombinedAnalytics_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCombinedAnalytics();
            return from_candid_CombinedAnalytics_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfigurationDistribution(): Promise<Array<ConfigurationDistribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfigurationDistribution();
                return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfigurationDistribution();
            return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFurnishingDistribution(): Promise<Array<FurnishingDistribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFurnishingDistribution();
                return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFurnishingDistribution();
            return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiriesByAgent(arg0: Principal): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiriesByAgent(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiriesByAgent(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiriesByProperty(arg0: string): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiriesByProperty(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiriesByProperty(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiry(arg0: string): Promise<Inquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiry(arg0);
                return from_candid_Inquiry_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiry(arg0);
            return from_candid_Inquiry_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByCategory(arg0: Category): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByCategory(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByCategory(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByCategoryAndType(arg0: Category, arg1: PropertyType): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByCategoryAndType(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0), to_candid_PropertyType_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByCategoryAndType(to_candid_Category_n12(this._uploadFile, this._downloadFile, arg0), to_candid_PropertyType_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByPropertyType(arg0: PropertyType): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByPropertyType(to_candid_PropertyType_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByPropertyType(to_candid_PropertyType_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: string): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_Property_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_Property_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuburbsForCity(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuburbsForCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuburbsForCity(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetToFreshDraft(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetToFreshDraft();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetToFreshDraft();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchAndFilterProperties(arg0: SearchCriteria): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAndFilterProperties(to_candid_SearchCriteria_n92(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAndFilterProperties(to_candid_SearchCriteria_n92(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAgent(arg0: Principal, arg1: string, arg2: string, arg3: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgent(arg0, arg1, arg2, to_candid_Role_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgent(arg0, arg1, arg2, to_candid_Role_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateInquiry(arg0: string, arg1: string, arg2: string, arg3: Source, arg4: Status__1, arg5: Principal, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiry(arg0, arg1, arg2, to_candid_Source_n10(this._uploadFile, this._downloadFile, arg3), to_candid_Status__1_n94(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiry(arg0, arg1, arg2, to_candid_Source_n10(this._uploadFile, this._downloadFile, arg3), to_candid_Status__1_n94(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async updateProperty(arg0: string, arg1: string, arg2: string, arg3: Location, arg4: Coordinates, arg5: bigint, arg6: Category, arg7: PropertyType, arg8: Configuration, arg9: Furnishing, arg10: Status, arg11: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Category_n12(this._uploadFile, this._downloadFile, arg6), to_candid_PropertyType_n14(this._uploadFile, this._downloadFile, arg7), to_candid_Configuration_n16(this._uploadFile, this._downloadFile, arg8), to_candid_Furnishing_n18(this._uploadFile, this._downloadFile, arg9), to_candid_Status_n28(this._uploadFile, this._downloadFile, arg10), await to_candid_vec_n20(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Category_n12(this._uploadFile, this._downloadFile, arg6), to_candid_PropertyType_n14(this._uploadFile, this._downloadFile, arg7), to_candid_Configuration_n16(this._uploadFile, this._downloadFile, arg8), to_candid_Furnishing_n18(this._uploadFile, this._downloadFile, arg9), to_candid_Status_n28(this._uploadFile, this._downloadFile, arg10), await to_candid_vec_n20(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
}
function from_candid_CategoryDistribution_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryDistribution): CategoryDistribution {
    return from_candid_record_n81(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_CombinedAnalytics_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CombinedAnalytics): CombinedAnalytics {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_ConfigurationDistribution_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConfigurationDistribution): ConfigurationDistribution {
    return from_candid_record_n78(_uploadFile, _downloadFile, value);
}
function from_candid_Configuration_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Configuration): Configuration {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FurnishingDistribution_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FurnishingDistribution): FurnishingDistribution {
    return from_candid_record_n75(_uploadFile, _downloadFile, value);
}
function from_candid_Furnishing_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Furnishing): Furnishing {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_PricingHeatmap_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PricingHeatmap): PricingHeatmap {
    return from_candid_record_n84(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyDensity_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyDensity): PropertyDensity {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyTypeDistribution_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyTypeDistribution): PropertyTypeDistribution {
    return from_candid_record_n88(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_Property_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Promise<Property> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_RegionType_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegionType): RegionType {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_RegionalDistribution_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegionalDistribution): RegionalDistribution {
    return from_candid_record_n91(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Source_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Source): Source {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    title: string;
    propertyType: _PropertyType;
    listedBy: Principal;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    category: _Category;
    configuration: _Configuration;
    price: bigint;
    furnishing: _Furnishing;
    location: _Location;
    coordinates: _Coordinates;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    status: Status;
    title: string;
    propertyType: PropertyType;
    listedBy: Principal;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    category: Category;
    configuration: Configuration;
    price: bigint;
    furnishing: Furnishing;
    location: Location;
    coordinates: Coordinates;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_Status_n37(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: from_candid_PropertyType_n39(_uploadFile, _downloadFile, value.propertyType),
        listedBy: value.listedBy,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        category: from_candid_Category_n41(_uploadFile, _downloadFile, value.category),
        configuration: from_candid_Configuration_n43(_uploadFile, _downloadFile, value.configuration),
        price: value.price,
        furnishing: from_candid_Furnishing_n45(_uploadFile, _downloadFile, value.furnishing),
        location: value.location,
        coordinates: value.coordinates,
        images: await from_candid_vec_n47(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    active: boolean;
    contactInfo: string;
    name: string;
    createdAt: _Time;
    role: _Role;
    updatedAt: _Time;
}): {
    id: Principal;
    active: boolean;
    contactInfo: string;
    name: string;
    createdAt: Time;
    role: Role;
    updatedAt: Time;
} {
    return {
        id: value.id,
        active: value.active,
        contactInfo: value.contactInfo,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n53(_uploadFile, _downloadFile, value.role),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: _Status__1;
    contactInfo: string;
    source: _Source;
    assignedAgent: Principal;
    createdAt: _Time;
    propertyId: string;
    updatedAt: _Time;
    notes: string;
}): {
    id: string;
    customerName: string;
    status: Status__1;
    contactInfo: string;
    source: Source;
    assignedAgent: Principal;
    createdAt: Time;
    propertyId: string;
    updatedAt: Time;
    notes: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_Status__1_n59(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        source: from_candid_Source_n61(_uploadFile, _downloadFile, value.source),
        assignedAgent: value.assignedAgent,
        createdAt: value.createdAt,
        propertyId: value.propertyId,
        updatedAt: value.updatedAt,
        notes: value.notes
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyDensity: Array<_PropertyDensity>;
    furnishingDistribution: Array<_FurnishingDistribution>;
    configurationDistribution: Array<_ConfigurationDistribution>;
    categoryDistribution: Array<_CategoryDistribution>;
    pricingHeatmap: Array<_PricingHeatmap>;
    propertyTypeDistribution: Array<_PropertyTypeDistribution>;
    regionalDistribution: Array<_RegionalDistribution>;
}): {
    propertyDensity: Array<PropertyDensity>;
    furnishingDistribution: Array<FurnishingDistribution>;
    configurationDistribution: Array<ConfigurationDistribution>;
    categoryDistribution: Array<CategoryDistribution>;
    pricingHeatmap: Array<PricingHeatmap>;
    propertyTypeDistribution: Array<PropertyTypeDistribution>;
    regionalDistribution: Array<RegionalDistribution>;
} {
    return {
        propertyDensity: from_candid_vec_n68(_uploadFile, _downloadFile, value.propertyDensity),
        furnishingDistribution: from_candid_vec_n73(_uploadFile, _downloadFile, value.furnishingDistribution),
        configurationDistribution: from_candid_vec_n76(_uploadFile, _downloadFile, value.configurationDistribution),
        categoryDistribution: from_candid_vec_n79(_uploadFile, _downloadFile, value.categoryDistribution),
        pricingHeatmap: from_candid_vec_n82(_uploadFile, _downloadFile, value.pricingHeatmap),
        propertyTypeDistribution: from_candid_vec_n86(_uploadFile, _downloadFile, value.propertyTypeDistribution),
        regionalDistribution: from_candid_vec_n89(_uploadFile, _downloadFile, value.regionalDistribution)
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    propertyCount: bigint;
    regionType: _RegionType;
}): {
    region: string;
    propertyCount: bigint;
    regionType: RegionType;
} {
    return {
        region: value.region,
        propertyCount: value.propertyCount,
        regionType: from_candid_RegionType_n71(_uploadFile, _downloadFile, value.regionType)
    };
}
function from_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    furnishedCount: bigint;
    unfurnishedCount: bigint;
    semiFurnishedCount: bigint;
    regionType: _RegionType;
}): {
    region: string;
    furnishedCount: bigint;
    unfurnishedCount: bigint;
    semiFurnishedCount: bigint;
    regionType: RegionType;
} {
    return {
        region: value.region,
        furnishedCount: value.furnishedCount,
        unfurnishedCount: value.unfurnishedCount,
        semiFurnishedCount: value.semiFurnishedCount,
        regionType: from_candid_RegionType_n71(_uploadFile, _downloadFile, value.regionType)
    };
}
function from_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    bungalowCount: bigint;
    bhk4Count: bigint;
    bhk1_5Count: bigint;
    bhk2Count: bigint;
    bhk2_5Count: bigint;
    rk1Count: bigint;
    independentHouseCount: bigint;
    jodiFlatCount: bigint;
    bhk5Count: bigint;
    bhk3_5Count: bigint;
    bhk3Count: bigint;
    bhk1Count: bigint;
    regionType: _RegionType;
    duplexCount: bigint;
    penthouseCount: bigint;
}): {
    region: string;
    bungalowCount: bigint;
    bhk4Count: bigint;
    bhk1_5Count: bigint;
    bhk2Count: bigint;
    bhk2_5Count: bigint;
    rk1Count: bigint;
    independentHouseCount: bigint;
    jodiFlatCount: bigint;
    bhk5Count: bigint;
    bhk3_5Count: bigint;
    bhk3Count: bigint;
    bhk1Count: bigint;
    regionType: RegionType;
    duplexCount: bigint;
    penthouseCount: bigint;
} {
    return {
        region: value.region,
        bungalowCount: value.bungalowCount,
        bhk4Count: value.bhk4Count,
        bhk1_5Count: value.bhk1_5Count,
        bhk2Count: value.bhk2Count,
        bhk2_5Count: value.bhk2_5Count,
        rk1Count: value.rk1Count,
        independentHouseCount: value.independentHouseCount,
        jodiFlatCount: value.jodiFlatCount,
        bhk5Count: value.bhk5Count,
        bhk3_5Count: value.bhk3_5Count,
        bhk3Count: value.bhk3Count,
        bhk1Count: value.bhk1Count,
        regionType: from_candid_RegionType_n71(_uploadFile, _downloadFile, value.regionType),
        duplexCount: value.duplexCount,
        penthouseCount: value.penthouseCount
    };
}
function from_candid_record_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    resaleCount: bigint;
    rentalCount: bigint;
    regionType: _RegionType;
    underConstructionCount: bigint;
}): {
    region: string;
    resaleCount: bigint;
    rentalCount: bigint;
    regionType: RegionType;
    underConstructionCount: bigint;
} {
    return {
        region: value.region,
        resaleCount: value.resaleCount,
        rentalCount: value.rentalCount,
        regionType: from_candid_RegionType_n71(_uploadFile, _downloadFile, value.regionType),
        underConstructionCount: value.underConstructionCount
    };
}
function from_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    averagePrice: [] | [bigint];
    priceRange: {
        maxPrice: [] | [bigint];
        minPrice: [] | [bigint];
    };
    regionType: _RegionType;
}): {
    region: string;
    averagePrice?: bigint;
    priceRange: {
        maxPrice?: bigint;
        minPrice?: bigint;
    };
    regionType: RegionType;
} {
    return {
        region: value.region,
        averagePrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.averagePrice)),
        priceRange: from_candid_record_n85(_uploadFile, _downloadFile, value.priceRange),
        regionType: from_candid_RegionType_n71(_uploadFile, _downloadFile, value.regionType)
    };
}
function from_candid_record_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxPrice: [] | [bigint];
    minPrice: [] | [bigint];
}): {
    maxPrice?: bigint;
    minPrice?: bigint;
} {
    return {
        maxPrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.maxPrice)),
        minPrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.minPrice))
    };
}
function from_candid_record_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    commercialCount: bigint;
    industrialCount: bigint;
    residentialCount: bigint;
    regionType: _RegionType;
}): {
    region: string;
    commercialCount: bigint;
    industrialCount: bigint;
    residentialCount: bigint;
    regionType: RegionType;
} {
    return {
        region: value.region,
        commercialCount: value.commercialCount,
        industrialCount: value.industrialCount,
        residentialCount: value.residentialCount,
        regionType: from_candid_RegionType_n71(_uploadFile, _downloadFile, value.regionType)
    };
}
function from_candid_record_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: string;
    averagePrice: [] | [bigint];
    priceRange: {
        maxPrice: [] | [bigint];
        minPrice: [] | [bigint];
    };
    furnishingDistribution: {
        semiFurnished: bigint;
        furnished: bigint;
        unfurnished: bigint;
    };
    configurationDistribution: {
        rk1: bigint;
        bhk1: bigint;
        bhk2: bigint;
        bhk3: bigint;
        bhk4: bigint;
        bhk5: bigint;
        penthouse: bigint;
        jodiFlat: bigint;
        bhk1_5: bigint;
        bhk2_5: bigint;
        bhk3_5: bigint;
        bungalow: bigint;
        independentHouse: bigint;
        duplex: bigint;
    };
    categoryDistribution: {
        rental: bigint;
        resale: bigint;
        underConstruction: bigint;
    };
    propertyCount: bigint;
    propertyTypeDistribution: {
        commercial: bigint;
        residential: bigint;
        industrial: bigint;
    };
    regionType: _RegionType;
}): {
    region: string;
    averagePrice?: bigint;
    priceRange: {
        maxPrice?: bigint;
        minPrice?: bigint;
    };
    furnishingDistribution: {
        semiFurnished: bigint;
        furnished: bigint;
        unfurnished: bigint;
    };
    configurationDistribution: {
        rk1: bigint;
        bhk1: bigint;
        bhk2: bigint;
        bhk3: bigint;
        bhk4: bigint;
        bhk5: bigint;
        penthouse: bigint;
        jodiFlat: bigint;
        bhk1_5: bigint;
        bhk2_5: bigint;
        bhk3_5: bigint;
        bungalow: bigint;
        independentHouse: bigint;
        duplex: bigint;
    };
    categoryDistribution: {
        rental: bigint;
        resale: bigint;
        underConstruction: bigint;
    };
    propertyCount: bigint;
    propertyTypeDistribution: {
        commercial: bigint;
        residential: bigint;
        industrial: bigint;
    };
    regionType: RegionType;
} {
    return {
        region: value.region,
        averagePrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.averagePrice)),
        priceRange: from_candid_record_n85(_uploadFile, _downloadFile, value.priceRange),
        furnishingDistribution: value.furnishingDistribution,
        configurationDistribution: value.configurationDistribution,
        categoryDistribution: value.categoryDistribution,
        propertyCount: value.propertyCount,
        propertyTypeDistribution: value.propertyTypeDistribution,
        regionType: from_candid_RegionType_n71(_uploadFile, _downloadFile, value.regionType)
    };
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rented: null;
} | {
    sold: null;
} | {
    underContract: null;
} | {
    available: null;
}): Status {
    return "rented" in value ? Status.rented : "sold" in value ? Status.sold : "underContract" in value ? Status.underContract : "available" in value ? Status.available : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    residential: null;
} | {
    industrial: null;
}): PropertyType {
    return "commercial" in value ? PropertyType.commercial : "residential" in value ? PropertyType.residential : "industrial" in value ? PropertyType.industrial : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rental: null;
} | {
    resale: null;
} | {
    underConstruction: null;
}): Category {
    return "rental" in value ? Category.rental : "resale" in value ? Category.resale : "underConstruction" in value ? Category.underConstruction : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rk1: null;
} | {
    bhk1: null;
} | {
    bhk2: null;
} | {
    bhk3: null;
} | {
    bhk4: null;
} | {
    bhk5: null;
} | {
    penthouse: null;
} | {
    jodiFlat: null;
} | {
    bhk1_5: null;
} | {
    bhk2_5: null;
} | {
    bhk3_5: null;
} | {
    bungalow: null;
} | {
    independentHouse: null;
} | {
    duplex: null;
}): Configuration {
    return "rk1" in value ? Configuration.rk1 : "bhk1" in value ? Configuration.bhk1 : "bhk2" in value ? Configuration.bhk2 : "bhk3" in value ? Configuration.bhk3 : "bhk4" in value ? Configuration.bhk4 : "bhk5" in value ? Configuration.bhk5 : "penthouse" in value ? Configuration.penthouse : "jodiFlat" in value ? Configuration.jodiFlat : "bhk1_5" in value ? Configuration.bhk1_5 : "bhk2_5" in value ? Configuration.bhk2_5 : "bhk3_5" in value ? Configuration.bhk3_5 : "bungalow" in value ? Configuration.bungalow : "independentHouse" in value ? Configuration.independentHouse : "duplex" in value ? Configuration.duplex : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    semiFurnished: null;
} | {
    furnished: null;
} | {
    unfurnished: null;
}): Furnishing {
    return "semiFurnished" in value ? Furnishing.semiFurnished : "furnished" in value ? Furnishing.furnished : "unfurnished" in value ? Furnishing.unfurnished : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    agent: null;
} | {
    juniorAgent: null;
} | {
    assistant: null;
}): Role {
    return "admin" in value ? Role.admin : "agent" in value ? Role.agent : "juniorAgent" in value ? Role.juniorAgent : "assistant" in value ? Role.assistant : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    closed: null;
} | {
    followUp: null;
} | {
    inProgress: null;
}): Status__1 {
    return "new" in value ? Status__1.new : "closed" in value ? Status__1.closed : "followUp" in value ? Status__1.followUp : "inProgress" in value ? Status__1.inProgress : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referral: null;
} | {
    website: null;
} | {
    walkIn: null;
} | {
    phone: null;
} | {
    socialMedia: null;
}): Source {
    return "referral" in value ? Source.referral : "website" in value ? Source.website : "walkIn" in value ? Source.walkIn : "phone" in value ? Source.phone : "socialMedia" in value ? Source.socialMedia : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    area: null;
} | {
    city: null;
} | {
    neighborhood: null;
} | {
    zone: null;
} | {
    suburb: null;
}): RegionType {
    return "area" in value ? RegionType.area : "city" in value ? RegionType.city : "neighborhood" in value ? RegionType.neighborhood : "zone" in value ? RegionType.zone : "suburb" in value ? RegionType.suburb : value;
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Promise<Array<Property>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Property_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n48(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyDensity>): Array<PropertyDensity> {
    return value.map((x)=>from_candid_PropertyDensity_n69(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FurnishingDistribution>): Array<FurnishingDistribution> {
    return value.map((x)=>from_candid_FurnishingDistribution_n74(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConfigurationDistribution>): Array<ConfigurationDistribution> {
    return value.map((x)=>from_candid_ConfigurationDistribution_n77(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryDistribution>): Array<CategoryDistribution> {
    return value.map((x)=>from_candid_CategoryDistribution_n80(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PricingHeatmap>): Array<PricingHeatmap> {
    return value.map((x)=>from_candid_PricingHeatmap_n83(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyTypeDistribution>): Array<PropertyTypeDistribution> {
    return value.map((x)=>from_candid_PropertyTypeDistribution_n87(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegionalDistribution>): Array<RegionalDistribution> {
    return value.map((x)=>from_candid_RegionalDistribution_n90(_uploadFile, _downloadFile, x));
}
function to_candid_AdvancedFilter_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdvancedFilter): _AdvancedFilter {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Configuration_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Configuration): _Configuration {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Furnishing_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Furnishing): _Furnishing {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SearchCriteria_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchCriteria): _SearchCriteria {
    return to_candid_record_n93(_uploadFile, _downloadFile, value);
}
function to_candid_Source_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Source): _Source {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n95(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categories: Array<Category>;
    configurations: Array<Configuration>;
    propertyTypes: Array<PropertyType>;
    statuses: Array<Status>;
    locations: Array<Location>;
    coordinateFilters: Array<{
        lat: number;
        lng: number;
        radius: number;
    }>;
    furnishings: Array<Furnishing>;
    priceRanges: Array<[bigint | null, bigint | null]>;
}): {
    categories: Array<_Category>;
    configurations: Array<_Configuration>;
    propertyTypes: Array<_PropertyType>;
    statuses: Array<_Status>;
    locations: Array<_Location>;
    coordinateFilters: Array<{
        lat: number;
        lng: number;
        radius: number;
    }>;
    furnishings: Array<_Furnishing>;
    priceRanges: Array<[[] | [bigint], [] | [bigint]]>;
} {
    return {
        categories: to_candid_vec_n24(_uploadFile, _downloadFile, value.categories),
        configurations: to_candid_vec_n25(_uploadFile, _downloadFile, value.configurations),
        propertyTypes: to_candid_vec_n26(_uploadFile, _downloadFile, value.propertyTypes),
        statuses: to_candid_vec_n27(_uploadFile, _downloadFile, value.statuses),
        locations: value.locations,
        coordinateFilters: value.coordinateFilters,
        furnishings: to_candid_vec_n30(_uploadFile, _downloadFile, value.furnishings),
        priceRanges: to_candid_vec_n31(_uploadFile, _downloadFile, value.priceRanges)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat?: number;
    lng?: number;
    status?: Status;
    roadName?: string;
    propertyType?: PropertyType;
    area?: string;
    city?: string;
    maxPrice?: bigint;
    suburb?: string;
    category?: Category;
    radius?: number;
    configuration?: Configuration;
    minPrice?: bigint;
    furnishing?: Furnishing;
}): {
    lat: [] | [number];
    lng: [] | [number];
    status: [] | [_Status];
    roadName: [] | [string];
    propertyType: [] | [_PropertyType];
    area: [] | [string];
    city: [] | [string];
    maxPrice: [] | [bigint];
    suburb: [] | [string];
    category: [] | [_Category];
    radius: [] | [number];
    configuration: [] | [_Configuration];
    minPrice: [] | [bigint];
    furnishing: [] | [_Furnishing];
} {
    return {
        lat: value.lat ? candid_some(value.lat) : candid_none(),
        lng: value.lng ? candid_some(value.lng) : candid_none(),
        status: value.status ? candid_some(to_candid_Status_n28(_uploadFile, _downloadFile, value.status)) : candid_none(),
        roadName: value.roadName ? candid_some(value.roadName) : candid_none(),
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n14(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        area: value.area ? candid_some(value.area) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        suburb: value.suburb ? candid_some(value.suburb) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n12(_uploadFile, _downloadFile, value.category)) : candid_none(),
        radius: value.radius ? candid_some(value.radius) : candid_none(),
        configuration: value.configuration ? candid_some(to_candid_Configuration_n16(_uploadFile, _downloadFile, value.configuration)) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none(),
        furnishing: value.furnishing ? candid_some(to_candid_Furnishing_n18(_uploadFile, _downloadFile, value.furnishing)) : candid_none()
    };
}
function to_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint | null, bigint | null]): [[] | [bigint], [] | [bigint]] {
    return [
        to_candid_opt_n33(_uploadFile, _downloadFile, value[0]),
        to_candid_opt_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Source): {
    referral: null;
} | {
    website: null;
} | {
    walkIn: null;
} | {
    phone: null;
} | {
    socialMedia: null;
} {
    return value == Source.referral ? {
        referral: null
    } : value == Source.website ? {
        website: null
    } : value == Source.walkIn ? {
        walkIn: null
    } : value == Source.phone ? {
        phone: null
    } : value == Source.socialMedia ? {
        socialMedia: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    rental: null;
} | {
    resale: null;
} | {
    underConstruction: null;
} {
    return value == Category.rental ? {
        rental: null
    } : value == Category.resale ? {
        resale: null
    } : value == Category.underConstruction ? {
        underConstruction: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    commercial: null;
} | {
    residential: null;
} | {
    industrial: null;
} {
    return value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.residential ? {
        residential: null
    } : value == PropertyType.industrial ? {
        industrial: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Configuration): {
    rk1: null;
} | {
    bhk1: null;
} | {
    bhk2: null;
} | {
    bhk3: null;
} | {
    bhk4: null;
} | {
    bhk5: null;
} | {
    penthouse: null;
} | {
    jodiFlat: null;
} | {
    bhk1_5: null;
} | {
    bhk2_5: null;
} | {
    bhk3_5: null;
} | {
    bungalow: null;
} | {
    independentHouse: null;
} | {
    duplex: null;
} {
    return value == Configuration.rk1 ? {
        rk1: null
    } : value == Configuration.bhk1 ? {
        bhk1: null
    } : value == Configuration.bhk2 ? {
        bhk2: null
    } : value == Configuration.bhk3 ? {
        bhk3: null
    } : value == Configuration.bhk4 ? {
        bhk4: null
    } : value == Configuration.bhk5 ? {
        bhk5: null
    } : value == Configuration.penthouse ? {
        penthouse: null
    } : value == Configuration.jodiFlat ? {
        jodiFlat: null
    } : value == Configuration.bhk1_5 ? {
        bhk1_5: null
    } : value == Configuration.bhk2_5 ? {
        bhk2_5: null
    } : value == Configuration.bhk3_5 ? {
        bhk3_5: null
    } : value == Configuration.bungalow ? {
        bungalow: null
    } : value == Configuration.independentHouse ? {
        independentHouse: null
    } : value == Configuration.duplex ? {
        duplex: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Furnishing): {
    semiFurnished: null;
} | {
    furnished: null;
} | {
    unfurnished: null;
} {
    return value == Furnishing.semiFurnished ? {
        semiFurnished: null
    } : value == Furnishing.furnished ? {
        furnished: null
    } : value == Furnishing.unfurnished ? {
        unfurnished: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    rented: null;
} | {
    sold: null;
} | {
    underContract: null;
} | {
    available: null;
} {
    return value == Status.rented ? {
        rented: null
    } : value == Status.sold ? {
        sold: null
    } : value == Status.underContract ? {
        underContract: null
    } : value == Status.available ? {
        available: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    agent: null;
} | {
    juniorAgent: null;
} | {
    assistant: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.agent ? {
        agent: null
    } : value == Role.juniorAgent ? {
        juniorAgent: null
    } : value == Role.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    new: null;
} | {
    closed: null;
} | {
    followUp: null;
} | {
    inProgress: null;
} {
    return value == Status__1.new ? {
        new_: null
    } : value == Status__1.closed ? {
        closed: null
    } : value == Status__1.followUp ? {
        followUp: null
    } : value == Status__1.inProgress ? {
        inProgress: null
    } : value;
}
async function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n21(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Category>): Array<_Category> {
    return value.map((x)=>to_candid_Category_n12(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Configuration>): Array<_Configuration> {
    return value.map((x)=>to_candid_Configuration_n16(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PropertyType>): Array<_PropertyType> {
    return value.map((x)=>to_candid_PropertyType_n14(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Status>): Array<_Status> {
    return value.map((x)=>to_candid_Status_n28(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Furnishing>): Array<_Furnishing> {
    return value.map((x)=>to_candid_Furnishing_n18(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint | null, bigint | null]>): Array<[[] | [bigint], [] | [bigint]]> {
    return value.map((x)=>to_candid_tuple_n32(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
